$schema: ./cache/schemas/tasks.json
tasks:
  storybook:
    command: storybook dev -p 6006
    preset: server
  storybook.build:
    command: storybook build
    inputs:
      - .storybok
      - src
    outputs:
      - storybook-static
    deps:
      - build
inheritedBy:
  tag: storybook
