tasks:
  create:
    script: docker network create traefik-network || true
    options:
      runInCI: false
  infra:
    command: docker compose up --build
    preset: server
    deps:
      - create
